### ISSUE TITLE
How to use multiple view controllers

### ISSUE THREAD

**Issue by iril7Langit** [aryaxt/ScrollPager#21]
Hello, how to show view controllers instead of UIView(UILabel) on each page?

I've searched on Google that I can used container view controllers. But I'm a bit stuck to combined it with this library?

can you give me some hints how to implement it? or maybe examples code.

Thank you very much and sorry for my bad English.

best regards,

**Comment by aryaxt** [comment]
Hi,
Each ViewController has a property for its view, you could pass its view to the scroll pager.
You could either instantiate viewControllers in code, or have a container where you remove from main subview and pass their view to scrollpager

:beers: 

https://github.com/aryaxt/ScrollPager/issues/5

**Comment by glub** [comment]
No, it's better if you allow for viewcontrollers to be added. If you just pass in the UIView of the VC then you won't get notified when the viewWillAppear, viewWillDisappear, etc. It would be nice if you added an addSegmentsWithTitlesAndViewControllers

**Comment by aryaxt** [comment]
@glub  Allowing to add viewControllers instead of view doesn't change the issue where the VC events are getting called. The reason those events aren't called for you is that the viewControllers are not added as childViewControlles of your main ViewController

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instm/UIViewController/addChildViewController:

simply
```
addChildViewController(firstViewController)
addChildViewController(secondViewController)
```

Then add their views to ScrollPager and all your events will get triggered when appropriate
